<?php

	$list = [
		[
			'fullName' => 'Agatha MacDonald',
			'email' => 'Agatha@gmail.com',
			'phone' => '584-214-99',
			'role' => 'coach',
			'subject' => 'Java',
		],
		[
			'fullName' => 'Albert OConnor',
			'email' => 'Albert@gmail.com',
			'phone' => '367-253-19',
			'role' => 'student',
			'averageMark' => '100.0', 
		],
		[
			'fullName' => 'Matthew Turner',
			'email' => 'Matthew@gmail.com',
			'phone' => '658-842-92',
			'role' => 'student',
			'averageMark' => '80.5', 
		],
		[
			'fullName' => 'Pamela Fletcher',
			'email' => 'Pamela@gmail.com',
			'phone' => '614-315-12',
			'role' => 'student',
			'averageMark' => '95.2', 
		],
		[
			'fullName' => 'Stefania Backer',
			'email' => 'Stefania@gmail.com',
			'phone' => '183-993-92',
			'role' => 'student',
			'averageMark' => '45.9', 
		],
		[
			'fullName' => 'Norman Young',
			'email' => 'Norman@gmail.com',
			'phone' => '365-413-18',
			'role' => 'coach',
			'subject' => 'PHP', 
		],
		[
			'fullName' => 'Ophelia Stevenson',
			'email' => 'Ophelia@gmail.com',
			'phone' => '473-953-36',
			'role' => 'student',
			'averageMark' => '80.7', 
		],
		[
			'fullName' => 'James Allford',
			'email' => 'James@gmail.com',
			'phone' => '987-321-88',
			'role' => 'student',
			'averageMark' => '45.1', 
		],
		[
			'fullName' => 'Wilma Leapman',
			'email' => 'Wilma@gmail.com',
			'phone' => '987-654-32',
			'role' => 'student',
			'averageMark' => '50.5', 
		],
		[
			'fullName' => 'Stacey Longman',
			'email' => 'Stacey@gmail.com',
			'phone' => '453-222-88',
			'role' => 'coach',
			'subject' => 'HTML', 
		],
		[
			'fullName' => 'Johnson Lie',
			'email' => 'Johnson@gmail.com',
			'phone' => '466-324-88',
			'role' => 'coach',
			'subject' => 'HTML', 
		],
		[
			'fullName' => 'Taylor Moore',
			'email' => 'Taylor@gmail.com',
			'phone' => '984-374-28',
			'role' => 'admin',
			'workingDay' => 'Monday', 
		],
		[
			'fullName' => 'Wilson Miller',
			'email' => 'Taylor@gmail.com',
			'phone' => '984-374-28',
			'role' => 'admin',
			'workingDay' => 'Tuesday', 
		],
	]
